version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r lambda/requirements.txt -t ./lambda/
  pre_build:
    commands:
      - echo Packaging Lambda function...
      - cd lambda
      - zip -r ../lambda-deployment-package.zip .
      - cd ..
  build:
    commands:
      - echo Deploying Lambda function...
      - aws lambda update-function-code --function-name TradingBotFunction --zip-file fileb://lambda-deployment-package.zip
      - echo Triggering SageMaker training job...
      - python sagemaker/train.py
artifacts:
  files:
    - lambda-deployment-package.zip
