
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  TradingBotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bot.trading_bot.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Timeout: 60
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SYMBOL: "EURUSD"
          TIMEFRAME: "M1"
            