name: Deploy Trading Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      S3_BUCKET: mike-trading-bot-artifacts
      LAMBDA_FUNCTION_NAME: MikeTradingBotFunction
      SAGEMAKER_ROLE: arn:aws:iam::980705396664:role/SageMakerExecutionRole

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies for Lambda
    - name: Install Lambda dependencies
      run: |
        cd lambda
        pip install -r requirements.txt -t .
        cd ..

    # Step 4: Package Lambda function
    - name: Package Lambda function
      run: |
        cd lambda
        zip -r ../lambda-deployment-package.zip .
        cd ..

    # Step 5: Deploy Lambda function
    - name: Deploy Lambda function
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: $AWS_REGION
        function-name: $LAMBDA_FUNCTION_NAME
        zip-file: lambda-deployment-package.zip

    # Step 6: Trigger SageMaker training
    - name: Trigger SageMaker training
      run: |
        pip install boto3
        python sagemaker/train.py
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
