name: Deploy Trading Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest

    env:
      LAMBDA_FUNCTION_NAME: MikeTradingBotFunction
      AWS_REGION: us-east-1

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r lambda/requirements.txt -t ./lambda/

    # Step 4: Package Lambda function
    - name: Package Lambda function
      run: |
        cd lambda
        zip -r ../lambda-deployment-package.zip ./*
        cd ..

    # Step 5: Validate zip file
    - name: Validate zip file contents
      run: |
        unzip -l lambda-deployment-package.zip

    # Step 6: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: $AWS_REGION

    # Step 7: Deploy Lambda function using AWS CLI
    - name: Deploy Lambda function
      run: |
        aws lambda update-function-code \
          --function-name $LAMBDA_FUNCTION_NAME \
          --zip-file fileb://lambda-deployment-package.zip
